language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --prefer-source --no-interaction
    - mkdir -p build/logs

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist
    - php vendor/bin/phpcs -n --standard=PSR2 --extensions=php --ignore=*/vendor/* .
    - php vendor/bin/phpmd  --suffixes php --exclude vendor . text codesize,naming,controversial,design
    - php vendor/bin/phpcpd --exclude vendor --exclude tests .
    - php vendor/bin/pdepend --ignore=vendor,tests --summary-xml=build/logs/summary.xml --jdepend-chart=build/logs/jdepend.svg --overview-pyramid=build/logs/pyramid.svg .

after_script:
    - php vendor/bin/coveralls -v
